# This is part of our Halloween setup where the Trick or Treaters
# will press a button to get a prize delivered.
#
substitutions:
  device_name: prize-delivery
  friendly_name: prize_delivery

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/esp8266.yaml

#Override the package:
esp8266:
  board: d1_mini  

web_server:
  port: 80


#======================================================

# A binary_sensor is a physical switch or button.
# The start button closes the relay which controls the motor
binary_sensor:
  - platform: gpio
    name: ${device_name} start
    pin:
      number: D4
      mode: input_pullup
      inverted: True
    id: button_start
    on_press:
      then:
        - switch.turn_on: relay
        - delay: 2s
        - switch.turn_on: led1
        - delay: 2s
        - switch.turn_on: led2
        - delay: 2s
        - switch.turn_on: led3
        - delay: 2s
        - switch.turn_on: led4
        - delay: 2s
        - switch.turn_on: led5

  # Microswitch at the home position..
  # The switch closes when the motor is at the home (load) position.
  - platform: gpio
    name: ${device_name} home
    pin:
      number: D2
      mode: input_pullup
      inverted: True
    id: button_home
    on_press:
      then:
        - switch.turn_off: relay
        - switch.turn_off: led1
        - switch.turn_off: led2
        - switch.turn_off: led3
        - switch.turn_off: led4
        - switch.turn_off: led5


switch:
  - platform: gpio
    name: ${device_name} relay
    pin:
      number: D1
      mode: output
    id: relay
    internal : true

  - platform: gpio
    name: ${device_name} led1
    pin:
      number: D0
      mode: output
    id: led1
    internal : true

  - platform: gpio
    name: ${device_name} led2
    pin:
      number: D6
      mode: output
    id: led2
    internal : true

  - platform: gpio
    name: ${device_name} led3
    pin:
      number: D7
      mode: output
    id: led3
    internal : true

  - platform: gpio
    name: ${device_name} led4
    pin:
      number: GPIO1     # Tx
      mode: output
    id: led4
    internal : true

  - platform: gpio
    name: ${device_name} led5
    pin:
      number: GPIO3     # Rx
      mode: output
    id: led5
    internal : true

status_led:
  pin:
    number: D5                    #External status LED
    inverted: True
    
    